export const Specialities = [
  "General Physician",
  "Pediatrician",
  "Cardiologist",
  "Dermatologist",
  "Gynecologist / Obstetrician",
  "Orthopedic Surgeon",
  "Neurologist",
  "Psychiatrist",
  "Ophthalmologist",
  "ENT Specialist",
  "Endocrinologist",
  "Oncologist",
  "Gastroenterologist",
  "Pulmonologist",
  "Nephrologist",
  "Urologist",
  "Rheumatologist",
  "General Surgeon",
  "Anesthesiologist",
  "Radiologist",
  "Pathologist",
  "Immunologist",
  "Geriatrician (Elderly care)",
  "Hematologist (Blood disorders)",
  "Plastic Surgeon",
  "Infectious Disease Specialist",
  "Emergency Medicine Specialist",
  "Sports Medicine Specialist",
  "Occupational Medicine Specialist",
  "Family Medicine Doctor"
]
