export const MessageConstants = {
  USER_REGISTER_SUCCESS: "User registered successfully.",
  DOCTOR_REGISTER_SUCCESS: "Docter registered successfully.",
  LOGIN_SUCCESS: "Login successful.",
  INTERNAL_SERVER_ERROR:
    "An internal server error occurred. Please try again later.",
  REFRESH_TOKEN_REQUIRED: "Refresh token is required.",
  INVALID_REFRESH_TOKEN: "Invalid refresh token. Please login again.",
  LOGIN_FAILED: "Login failed. Please check your credentials.",
  EMAIL_REQUIRED: "Email is required.",
  LOGOUT_SUCCESS: "Logged out successfully.",
  INVALID_CREDENTIALS: "Invalid credentials.",
  EMAIL_ALREADY_EXISTS: "Email already in use",
  OTP_SENT: "OTP sent successfully",
  INVALID_PASSWORD: "Wrong Password.",
  DOCTOR_APPROVAL_REQUIRED:
    "Your account requires administrator approval to perform this action",
  USER_NOT_FOUND: "User not found.",
  USER_ALREADY_EXISTS: "User with this email already exists",
  ACCESS_TOKEN_REFRESHED: "Access token refreshed successfully",
  REFRESH_TOKEN_FAILED: "Failed to refresh tokens.",
  FILE_NOT_UPLOADED: "No file uploaded.",
  DOCTOR_STATUS_UPDATED: "Doctor status updated successfully.",
  DOCTOR_BLOCKED: "Doctor blocked successfully.",
  DOCTOR_UNBLOCKED: "Doctor unblocked successfully.",
  USER_BLOCKED: "User blocked successfully.",
  USER_UNBLOCKED: "User unblocked successfully.",
  PROFILE_FETCHED_SUCCESS: "User profile fetched successfully.",
  DOCTOR_ID_NOT_FOUND: "Doctor ID not found",
  PROFILE_UPDATED_SUCCESS: "Profile updated sucessfully",
  DOCTOR_NOT_FOUND: "Doctor not found",
  DOCTOR_APPROVED: "Doctor approved successfully",
  DOCTOR_FETCH_SUCCESSFULL: "All doctors populated",
  ID_TOKEN_REQUIRED: "ID token is required.",
  GOOGLE_SIGNIN_SUCCESS: "Google Sign-In successful.",
  GOOGLE_SIGNIN_FAILED: "Google Sign-In failed. Please try again.",
  MISSING_REQUIRED_FIELDS: "Missing required fields",
  REGISTRATION_NUMBER_EXISTS: "Registration number already exists",
  DOCTOR_NOT_VERIFIED: "Doctor account is not verified yet",
  DOCTOR_VERIFIED: "Doctor verification status updated successfully",
  PENDING_VERIFICATIONS_FETCHED: "Pending verifications fetched successfully",
  INVALID_VERIFICATION_STATUS: "Invalid verification status",
  PROFILE_PICTURE_UPLOADED: "Profile picture uploaded",
  REQUIRED_FIELDS_MISSING: "Required field is missing",
  INVALID_DOCTOR: "Invalid Doctor",
  INVALID_PATIENT: "Invalid Patient",
  NO_AVAILABLE_SLOTS: "No available slot",
  BOOKING_NOT_FOUND: "Appointment not found",
  BOOKING_ALREADY_CANCELLED: "Booking already cancelled",
  INVALID_BOOKING_STATUS: "Invalid booking status",
  PERMISSION_DENIED: "PERMISSION_DENIED",
  UNAUTHORIZED: "Unauthorized user",
  APPOINTMENT_CREATED: "Appointment created successfully",
  APPOINTMENT_FETCHED: "Appointment fatched successfully",
  APPOINTMENT_CANCELLED: "Appointment cancelled successfully",
  APPOINTMENT_CONFIRMED: "Appointment confirmed successfully",
  APPOINTMENT_PAYMENT_FAILED: "Appointment payment failed",
  AVAILABLE_Doctors_FETCHED: "AVAILABLE_Doctors_FETCHED",
  SLOT_CREATED: "Slot created successfully",
  SLOT_BOOKED: "Slot Booked successfully",
  SUCCESS: "Operation successful",
  PAYMENT_ORDER_CREATED: "Payment order created successfully.",
  PAYMENT_VERIFIED: "Payment verified successfully.",
  PAYMENT_VERIFICATION_FAILED: "Payment verification failed.",
  USER_ID_NOT_FOUND: "User Id not found",
  PRESCRIPTION_CREATED: "Prescription Created Successfully",
  NOTIFICATION_NOT_FOUND: "Notification not found",
  DASHBOARD_STATS_FETCHED: "Dashboard statistics fetched successfully",
  EMAIL_SENDING_FAILED: "Failed to send email.",
  INVALID_BOOKING_FOR_VIDEO_CALL: "Invalid booking for video call.",
  BOOKING_UPDATE_FAILED: "Failed to update booking.",
  INVALID_SLOT: "Invalid slot ID.",
  INVALID_SUBSLOT_INDEX: "Invalid sub-slot index.",
  SLOT_ALREADY_BOOKED: "Selected time slot is already booked.",
  SLOT_UPDATE_FAILED: "Failed to update slot.",
  INVALID_USER_ID: "Invalid user ID.",
  NO_ACTIVE_APPOINTMENTS: "No active appointments found.",
  INVALID_BOOKING_ID: "Invalid booking ID.",
  NO_DOCTORS_FOUND: "No doctors found.",
  NO_AVAILABLE_DOCTORS: "No available doctors for the selected time.",
  INVALID_PAGINATION: "Invalid pagination parameters.",
  INVALID_DOCTOR_ID: "Invalid doctor ID.",
  FETCH_BOOKINGS_FAILED: "Failed to fetch bookings.",
  CHECK_BOOKING_FAILED: "Failed to check booking.",
  INVALID_ID: "Invalid ID provided.",
};
