export const MessageConstants = {
  USER_REGISTER_SUCCESS: "User registered successfully.",
  DOCTOR_REGISTER_SUCCESS: "Docter registered successfully.",
  LOGIN_SUCCESS: "Login successful.",
  INTERNAL_SERVER_ERROR:
    "An internal server error occurred. Please try again later.",
  REFRESH_TOKEN_REQUIRED: "Refresh token is required.",
  INVALID_REFRESH_TOKEN: "Invalid refresh token. Please login again.",
  LOGIN_FAILED: "Login failed. Please check your credentials.",
  EMAIL_REQUIRED: "Email is required.",
  LOGOUT_SUCCESS: "Logged out successfully.",
  INVALID_CREDENTIALS: "Invalid credentials.",
  EMAIL_ALREADY_EXISTS: "Email already in use",
  OTP_SENT: "OTP sent successfully",
  INVALID_PASSWORD: "Wrong Password.",
  DOCTOR_APPROVAL_REQUIRED:
    "Your account requires administrator approval to perform this action",
  USER_NOT_FOUND: "User not found.",
  USER_ALREADY_EXISTS: "User with this email already exists",
  ACCESS_TOKEN_REFRESHED: "Access token refreshed successfully",
  REFRESH_TOKEN_FAILED: "Failed to refresh tokens.",
  FILE_NOT_UPLOADED: "No file uploaded.",
  DOCTOR_STATUS_UPDATED: "Doctor status updated successfully.",
  DOCTOR_BLOCKED: "Doctor blocked successfully.",
  DOCTOR_UNBLOCKED: "Doctor unblocked successfully.",
  USER_BLOCKED: "User blocked successfully.",
  USER_UNBLOCKED: "User unblocked successfully.",
  PROFILE_FETCHED_SUCCESS: "User profile fetched successfully.",
  DOCTOR_ID_NOT_FOUND: "Doctor ID not found",
  PROFILE_UPDATED_SUCCESS: "Profile updated sucessfully",
  DOCTOR_NOT_FOUND: "Doctor not found",
  DOCTOR_APPROVED: "Doctor approved successfully",
  DOCTOR_FETCH_SUCCESSFULL: "All doctors populated",
  ID_TOKEN_REQUIRED: "ID token is required.",
  GOOGLE_SIGNIN_SUCCESS: "Google Sign-In successful.",
  GOOGLE_SIGNIN_FAILED: "Google Sign-In failed. Please try again.",
  MISSING_REQUIRED_FIELDS: "Missing required fields",
  REGISTRATION_NUMBER_EXISTS: "Registration number already exists",
  DOCTOR_NOT_VERIFIED: "Doctor account is not verified yet",
  DOCTOR_VERIFIED: "Doctor verification status updated successfully",
  PENDING_VERIFICATIONS_FETCHED: "Pending verifications fetched successfully",
  INVALID_VERIFICATION_STATUS: "Invalid verification status",
  PROFILE_PICTURE_UPLOADED: "Profile picture uploaded",
  REQUIRED_FIELDS_MISSING: "Required field is missing",
  INVALID_DOCTOR: "Invalid Doctor",
  INVALID_PATIENT: "Invalid Patient",
  NO_AVAILABLE_SLOTS: "No available slot",
  BOOKING_NOT_FOUND: "Appointment not found",
  BOOKING_ALREADY_CANCELLED: "Booking already cancelled",
  INVALID_BOOKING_STATUS: "Invalid booking status",
  PERMISSION_DENIED: "PERMISSION_DENIED",
  UNAUTHORIZED: "Unauthorized user",
  APPOINTMENT_CREATED: "Appointment created successfully",
  APPOINTMENT_FETCHED: "Appointment fatched successfully",
  APPOINTMENT_CANCELLED: "Appointment cancelled successfully",
  APPOINTMENT_CONFIRMED: "Appointment confirmed successfully",
  APPOINTMENT_PAYMENT_FAILED: "Appointment payment failed",
  AVAILABLE_Doctors_FETCHED: "AVAILABLE_Doctors_FETCHED",
  SLOT_CREATED: "Slot created successfully",
  SLOT_BOOKED: "Slot Booked successfully",
  SUCCESS: "Operation successful",
  PAYMENT_ORDER_CREATED: "Payment order created successfully.",
  PAYMENT_VERIFIED: "Payment verified successfully.",
  PAYMENT_VERIFICATION_FAILED: "Payment verification failed.",
  USER_ID_NOT_FOUND: "User Id not found",
  PRESCRIPTION_CREATED: "Prescription Created Successfully",
  NOTIFICATION_NOT_FOUND: "Notification not found",
  DASHBOARD_STATS_FETCHED: "Dashboard statistics fetched successfully",
  EMAIL_SENDING_FAILED: "Failed to send email.",
  INVALID_BOOKING_FOR_VIDEO_CALL: "Invalid booking for video call.",
  BOOKING_UPDATE_FAILED: "Failed to update booking.",
  INVALID_SLOT: "Invalid slot ID.",
  INVALID_SUBSLOT_INDEX: "Invalid sub-slot index.",
  SLOT_ALREADY_BOOKED: "Selected time slot is already booked.",
  SLOT_UPDATE_FAILED: "Failed to update slot.",
  INVALID_USER_ID: "Invalid user ID.",
  NO_ACTIVE_APPOINTMENTS: "No active appointments found.",
  INVALID_BOOKING_ID: "Invalid booking ID.",
  NO_DOCTORS_FOUND: "No doctors found.",
  NO_AVAILABLE_DOCTORS: "No available doctors for the selected time.",
  INVALID_PAGINATION: "Invalid pagination parameters.",
  INVALID_DOCTOR_ID: "Invalid doctor ID.",
  FETCH_BOOKINGS_FAILED: "Failed to fetch bookings.",
  CHECK_BOOKING_FAILED: "Failed to check booking.",
  INVALID_ID: "Invalid ID provided.",
  WALLET_NOT_FOUND : 'Wallet Amount not fount',
  INSUFFICIENT_BALANCE : 'Balance is insufficient in your wallet',
  PRESCRIPTION_NOT_FOUND : 'Prescription not found',
  CERTIFICATE_UPLOAD_FAILED : 'Certification upload failed',
  OTP_SEND : "OTP send successfully" ,
  EMAIL_AND_OTP_REQUIRED : "Email and OTP are required." ,
  INVALID_OTP : "Invalid OTP.",
  OTP_VERIFIED :"OTP verified and user registered successfully.",
  OTP_RESEND : "OTP resent successfully",
  PENDING_DOCTORS : "Pending doctors retrieved successfully",
  DOCTOR_VERIFICATION_STATUS_UPDATED: "Doctor verification status updated successfully",
  BLOCK_REASON_REQUIRED: "Block reason is required",
  ALL_DOCTORS_RETRIEVED: "All doctors retrieved successfully",
  ALL_USERS_RETRIEVED: "All users retrieved successfully",
  DOCTOR_ID_REQUIRED: "Doctor ID is required",
  USER_ID_REQUIRED: "User ID is required",
  DOCTOR_FETCHED_SUCCESSFULLY: "Doctor fetched successfully",
  DASHBOARD_DATA_FETCHED: "Dashboard data fetched successfully",
  INVALID_DATE_FORMAT: "Invalid date format. Please use ISO format (YYYY-MM-DD)",
  INVAID_FILTER_VALUE: "Invalid filter value. Must be 'daily', 'monthly', or 'yearly'",
  START_DATE_MUST_BE_BEFORE_END_DATE: "Start date must be before end date",
  PAYMENT_HISTORY_FETCHED: "Payment history fetched successfully",
  REVENUE_FETCHED: "Revenue fetched successfully",
  BOOKING_CHECK_COMPLETED: "Booking check completed successfully",
  BOOKING_FETCHED: "Booking fetched successfully",
  BOOKED_USER_POPULATED: "Booked user populated successfully",
  NO_PATIENTS_AVAILABLE: "No patients available ",
  USER_BOOKINGS_FETCHED: "User bookings fetched successfully",
  FAILED_BOOKING_RECORED: "Failed to create booking record",
  VIDEO_CALL_ROOM_CREATED: "Video call room created successfully",
  USER_WHO_MESSAGED_FETCHED: "Users who messaged fetched successfully",
  DOCTOR_WHO_MESSAGED_FETCHED: "Doctors who messaged fetched successfully",
  NOTIFICATION_FETCHED: "Notification fetched successfully",
  MARK_AS_READ: "Notification marked as read successfully",
  MARK_ALL_AS_READ: "All notifications marked as read successfully",
  ALL_NOTIFICATION_CLEARED: "All notifications cleared successfully",
  NOTIFICATION_DELETED: "Notification deleted successfully",
  PRESCRIPTION_FOUNTD: "Prescription found successfully",
  PRESCRIPTION_LISTED: "Prescriptions listed successfully",
  PDF_NOT_FOUND:"PDF file not found on server",
  APPOINTMENT_ID_REQUIRED: "Appointment ID is required",
  RATING_MUST_BE_BETWEEN_1_AND_5: "Rating must be between 1 and 5",
  REVIEW_SUBMITTED: "Review submitted successfully",
  REVIEW_NOT_FOUND: "Review not found",
  REVIEW_FETCHED: "Review fetched successfully",
  DOCTOR_AND_APPOINTMENT_ID_REQUIRED: "Doctor ID and Appointment ID are required",
  REVIEW_CKEKCED_COMPLETED: "Review check completed successfully",
  MAXIMUM_PATIENTS_REQUIRED: "Maximum patients must be at least 1",
  DOCTORS_CAN_ONLY_CREATE_SLOTS_FOR_THEMSELVES: "Doctors can only create slots for themselves",
  SLOT_ID_REQUIRED: "Slot ID is required",
  BOOKING_CANCELLED: "Booking cancelled successfully",
  SLOT_NOT_FOUND: "Slot not found",
  NO_BOOKINGS_TO_CANCEL: "No bookings to cancel",
  SLOT_FULLY_BOOKED: "Slot is fully booked",
  SLOT_IS_BLOCKED: "Slot is blocked",
  SLOT_DELETED: "Slot deleted successfully",
  SLOT_UPDATED: "Slot updated successfully",
  CANNOT_REDUCE_MAXIMUM_PATIENTS_BELOW_CURRENT_BOOKINGS: "Cannot reduce maximum patients below current bookings",
  SLOT_AVAILABILITY_CHECKED: "Slot availability checked successfully",
  FAILED_TO_CHECK_SLOT_AVAILABILITY: "Failed to check slot availability",
  DOCTOR_REGISTRATION_NUMBER_EXISTS: "Doctor registration number already exists",
  STATUS_CHANGED: "Status changed successfully",
  CERTIFICATE_UPLOADED: "Certificate uploaded successfully",
  CERTIFICATE_DELETED: "Certificate deleted successfully",
  FILE_NOT_FOUND: "File not found",
  SIGNEDOUT_SUCCESS: "Signed out successfully",
};
