export const MessageConstants = {
    USER_REGISTER_SUCCESS: "User registered successfully.",
    DOCTOR_REGISTER_SUCCESS: "Docter registered successfully.",
    LOGIN_SUCCESS: "Login successful.",
    INTERNAL_SERVER_ERROR: "An internal server error occurred. Please try again later.",
    REFRESH_TOKEN_REQUIRED: "Refresh token is required.",
    INVALID_REFRESH_TOKEN: "Invalid refresh token. Please login again.",
    LOGIN_FAILED: "Login failed. Please check your credentials.",
    EMAIL_REQUIRED: "Email is required.",
    LOGOUT_SUCCESS: "Logged out successfully.",
    INVALID_CREDENTIALS: "Invalid credentials.",
    EMAIL_ALREADY_EXISTS: 'Email already in use',
    OTP_SENT:'OTP sent successfully',
    INVALID_PASSWORD: "Wrong Password.",
    DOCTOR_APPROVAL_REQUIRED : "Your account requires administrator approval to perform this action",
    USER_NOT_FOUND: "User not found.",
    USER_ALREADY_EXISTS: "User with this email already exists",
    ACCESS_TOKEN_REFRESHED: "Access token refreshed successfully",
    REFRESH_TOKEN_FAILED: "Failed to refresh tokens.",
    FILE_NOT_UPLOADED: "No file uploaded.",
    DOCTOR_STATUS_UPDATED : 'Doctor status updated successfully.',
    DOCTOR_BLOCKED : 'Doctor blocked successfully.',
    DOCTOR_UNBLOCKED : 'Doctor unblocked successfully.',
    USER_BLOCKED: "User blocked successfully.",
    USER_UNBLOCKED: "User unblocked successfully.",
    PROFILE_FETCHED_SUCCESS : "User profile fetched successfully.",
    DOCTOR_ID_NOT_FOUND : "Doctor ID not found",
    PROFILE_UPDATED_SUCCESS:"Profile updated sucessfully",
    DOCTOR_NOT_FOUND:'Doctor not found',
    DOCTOR_APPROVED : 'Doctor approved successfully'
}